growmat/growmat/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^w/', include('w.urls', namespace="w")),
	url(r'^admin/', include(admin.site.urls)),
	
	url(r'', include('w.urls', namespace="w")),
]

growmat/w/urls.py
from django.conf.urls import url, include


from . import views

#from .models import InstrumentList
#from .views import InstrumentCreate, InstrumentUpdate, 
from .views import InstrumentDelete, RuleDelete, PeriodDelete

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<page>[0-9]+)/$', views.index, name='index'),
	
	url(r'^detail/(?P<page>[0-9]+)/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
	
	url(r'^archive/(?P<pk>[0-9]+)/$', views.archive, name='archive'),
	url(r'^archive/$', views.archive, name='archive'),
	

	url(r'^save/$', views.save, name='save'),
	
	url(r'^rule/$', views.rule, name='rule'),
	url(r'^rule/(?P<pk>[0-9]+)/$', views.rule, name='rule'),
	url(r'^rule_delete/(?P<pk>[0-9]+)/$', RuleDelete.as_view(), name='rule_delete'),
	
	url(r'^period/$', views.period, name='period'),
	url(r'^period/(?P<pk>[0-9]+)/$', views.period, name='period'),
	url(r'^period_delete/(?P<pk>[0-9]+)/$', PeriodDelete.as_view(), name='period_delete'),
	
	url(r'^instrument/$', views.instrument, name='instrument'),
	url(r'^instrument/(?P<pk>[0-9]+)/$', views.instrument, name='instrument'),
	url(r'^instrument_delete/(?P<pk>[0-9]+)/$', InstrumentDelete.as_view(), name='instrument_delete'),
	
	url(r'^webcam/(?P<pk>[0-9]+)/$', views.webcam, name='webcam'),
	url(r'^webcam/$', views.webcam, name='webcam'),
	
	#url(r'^(?P<instrument_id>[0-9]+)/$', views.instrument, name='instrument'),
	#url(r'^instrumentAdd/$', views.instrumentAdd, name='instrumentAdd'),
	#url(r'^list/$', InstrumentList.as_view()),
	#url(r'^c/$', InstrumentCreate.as_view(), name='c'),
	
	#url(r'^u/(?P<pk>[0-9]+)$', InstrumentUpdate.as_view(), name='u'),
	#url(r'^u/(?P<pk>[0-9]+)$', views.update(), name='u'),
	#url(r'^d/(?P<pk>[0-9]+)$', InstrumentDelete.as_view(), name='d'),
	#url(r'^d/(?P<pk>[0-9]+)$', InstrumentDelete.as_view()), name='d'),	
	#url(r'^list$', InstrumentList.as_view(), name='list'),
	
	#url(r'^', include('django.contrib.auth.urls')),
	url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
	url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'registration/logged_out2.html'}, name='logout'),

	
]

growmat/w/models.py
#from django.urls import reverse

from django.db import models
from django.forms import ModelForm
from django.views.generic import ListView
from django.views.generic import DetailView
from django.core.urlresolvers import reverse




# Create your models here.
class Instrument(models.Model):
	
	#INI = 1 << 0
	cNT = 1<<0
	cIV = 1<<1
	cA  = 1<<2
	cW  = 1<<3
	
	INSTRUMENT_TYPE = (
					(10, 'SYSTEM'),
					(0,  'MODBUS'),
     				(20, 'SCRIPT'),
                    (30, 'BTSPP2FILE'),
                    (40, 'RC'),
                    (50, 'GROWMATUTILS'),
         			#(30, 'HUMIDITYMETER'),
    			    #(40, 'DISTANCEMETER'),
    				#(50, 'PHMETER'),    				
	)
	
	INSTRUMENT_INDEX = (
					(0, '0'),
     				(1, '1'),
         			(2, '2'),
    			    (3, '3'),
    				(4, '4'),
    				(5, '5'),
     				(6, '6'),
         			(7, '7'),
    			    (8, '8'),
    				(9, '9'),
	)
	
	DATA_TYPE = (
					(0, 'int'),
     				(1, 'float'),
	)
	
		
	priority = models.FloatField(default=0, blank=True)
	manual = models.BooleanField(default=False, blank=True)
	address = models.IntegerField(default=0)
	type = models.IntegerField(choices=INSTRUMENT_TYPE, default=0)
	#index = models.IntegerField(choices=INSTRUMENT_INDEX, default=0)
	index = models.IntegerField(default=0)
	output = models.BooleanField(default = False, blank=True)
	datatype = models.IntegerField(choices=DATA_TYPE, default=0)
	name = models.CharField(default='NEW',  max_length=256)
	value = models.FloatField(default=0)
	status = models.IntegerField(default=1) 
	datetime = models.DateTimeField(null=True, blank=True) 
	
	#def get_absolute_url(self):
	#	return reverse('list', kwargs={'pk': self.pk})
	def get_fields(self):
		return [(field.name, field.value_to_string(self)) for field in Instrument._meta.fields]
	
	def NT(self):
		return self.status & Instrument.cNT
	def IV(self):
		return self.status & Instrument.cIV
	def A(self):
		return self.status & Instrument.cA
	def W(self):
		return self.status & Instrument.cW
	
	
	
class InstrumentForm(ModelForm):
    class Meta:
        model = Instrument
        fields = ['priority', 'manual', 'address', 'type', 'index', 'output', 'datatype','name', 'value', 'status', 'datetime']


class InstrumentList(ListView):
	model = Instrument
		#queryset = Instrument.objects.all()
		#fields = ['address', 'type', 'index', 'name', 'value', 'status', 'datetime']		
#class Choice(models.Model):
#    question = models.ForeignKey(Question)
#    choice_text = models.CharField(max_length=200)
#    votes = models.IntegerField(default=0)


class Period(models.Model):
	name = models.CharField(default='NEW',  max_length=256)
	time_from = models.TimeField()
	time_to = models.TimeField()
	description = models.CharField(null=True, blank=True,  max_length=256) 
	
	

class PeriodForm(ModelForm):
    class Meta:
        model = Period
        fields = ['name', 'time_from', 'time_to', 'description']	
        


class Rule(models.Model):	

	
	ATTRIBUTE_TYPE = (
					('VALUE', 'VALUE'),
     				('STATUS', 'STATUS'),
         			('NT', 'NT'),
    			    ('IV', 'IV'),
    			    ('W', 'WARNING'),
    			    ('A', 'ALARM'),
	)
	
	OPERATION_TYPE = (
					('<', '<'),
					('<=', '<='),
     				('==', '=='),
         			('>', '>'),
         			('>=', '>='),
    			    ('!=', '!='),
    			    ('and', 'AND'),
    			    ('or', 'OR'),
	)
	
	ACTION_TYPE = (
					('None', 'None'),
					('=', '='),
					('&', '&'),
					('& ~', '& ~'),
					('|', '|'),
					('| ~', '| ~'),
					('+', '+'),
					('-', '-'),
					('*', '*'),
					('/', '/'),
					('%', '%'),
	)
	
	priority = models.FloatField(default=0, blank=True)
	period = models.ForeignKey(Period)
	input = models.ForeignKey(Instrument, related_name='input_instrument')
	input_attribute = models.CharField(choices=ATTRIBUTE_TYPE, default=0, max_length=6)
	input_operation = models.CharField(choices=OPERATION_TYPE, default=0, max_length=2)
	input_parameter = models.FloatField(default=0, blank=True)
	output = models.ForeignKey(Instrument, related_name='output_instrument')
	output_attribute = models.CharField(choices=ATTRIBUTE_TYPE, default=0, max_length=6)
	output_action_true = models.CharField(choices=ACTION_TYPE, default='None', max_length=4)
	output_parameter_true = models.FloatField(default=0, blank=True)
	output_action_false = models.CharField(choices=ACTION_TYPE, default='None', max_length=4)
	output_parameter_false = models.FloatField(default=0, blank=True)
	description = models.CharField(null=True, blank=True,  max_length=256) 
	result = models.BooleanField(default=False, blank=True) 
	result0 = models.BooleanField(default=False, blank=True) 
	datetime = models.DateTimeField(null=True, blank=True) 
	once = models.BooleanField(default=False, blank=True) 

class RuleForm(ModelForm):
    class Meta:
        model = Rule
        fields = ['priority', 'period', 'input', 'input_attribute', 'input_operation', 'input_parameter', 'output', 'output_attribute', 'output_action_true', 'output_parameter_true', 'output_action_false', 'output_parameter_false', 'description', 'result', 'result0', 'datetime', 'once']
        
    def __init__(self, *args, **kwargs):
        super(RuleForm, self).__init__(*args, **kwargs)
        self.fields['input'].queryset = Instrument.objects.all()
        self.fields['input'].label_from_instance = lambda obj: "%s" % (obj.name)
        self.fields['output'].queryset = Instrument.objects.all()
        self.fields['output'].label_from_instance = lambda obj: "%s" % (obj.name)
        
        self.fields['period'].queryset = Period.objects.all()
        self.fields['period'].label_from_instance = lambda obj: "%s" % (obj.name)
        
        
class Archive(models.Model):	
	instrument = models.ForeignKey(Instrument)
	value = models.FloatField(default=0, null=True, blank=True)
	status = models.IntegerField(default=0, null=True, blank=True)
	datetime = models.DateTimeField(null=True, blank=True) 
	

	
	
	 

	

growmat/w/templates/w/base.html
<html>
	<head>
		<title>GROWMAT</title>
		
    </head>

	<body>
   		<h3>
   			{% if user.is_authenticated %}{{ user.username }} <a href="{% url 'w:logout' %}">logout</a>{% else %}<a href="{% url 'w:login' %}">Login</a>{% endif %}
			<br>	
   			<a href="{% url 'w:index' %}">GROWMAT</a>
			<a href="{% url 'w:instrument' %}">Instruments</a>
			<a href="{% url 'w:period' %}">Periods</a>
			<a href="{% url 'w:rule' %}">Rules</a>
			<a href="{% url 'w:archive' %}">Archives</a>
			<a href="{% url 'w:webcam' %}">Webcam</a>
 			{% if user.is_authenticated %}<a href="{% url 'w:save' %}">SAVE DB</a>{% endif %}
		</h3>

       {% block content %}

       {% endblock %} 
    </body>
</html>

growmat/w/templates/w/detail.html
{% load staticfiles %}
<html>
	<head>
		<title>GROWMAT</title>
		<meta name="viewport" content="width=device-width">
		<link rel="stylesheet" type="text/css" href="{% static 'w/style.css' %}">
    </head>

<body>
<table>
<tr>
<td>
<a href="{% url 'w:index' page %}"><button class="label">GROWMAT</button></a>
</td>
<td>
<a href="{% url 'w:instrument' %}"><button class="label">System</button></a>
</td>
<td>
<a href="{% url 'w:webcam' 0 %}"><button class="label">Webcam<br>0</button></a> 
</td>
<td>
<a href="{% url 'w:webcam' 1 %}"><button class="label">Webcam<br>1</button></a>
</td>
</tr>
</table>

<hr>
{% comment %}
<h3>
{% if user.is_authenticated %}{{ user.username }} <a href="{% url 'w:logout' %}">logout</a>{% else %}<a href="{% url 'w:login' %}">Login</a>{% endif %}
<br>
<a href="{% url 'w:index' %}">GROWMAT</a>
<a href="{% url 'w:instrument' %}">System</a>
</h3>
<hr>
{% endcomment %}
{% comment %}
{% block content %}

<table border=1>
		<tr><th>NAME</th><th>VALUE</th><th>STATUS</th></tr>
       {% for instrument in instruments %}
			{% if instrument.status > 0 and instrument.status < 4 %}
        		<tr class="NT">
        	{% elif instrument.status = 4 %}
        		<tr class="W">
        	{% elif instrument.status = 8 %}
        		<tr class="A">
        	{% else %}
        		<tr>
        	{% endif %}
            	<td>{{ instrument.name }}</td>
               	<td>{{ instrument.value }} </td>
            	<td>{{ instrument.status }} </td>
            </tr>
            
        {% endfor %}
 </table>
{% endblock %}

     {% comment %}	
<table>
	<tr>
	{% if instrument.NT %}
        		<td class="NT">
        	{% elif instrument.IV %}
        		<td class="IV">
        	{% elif instrument.W %}
        		<td class="W">
        	{% elif instrument.A %}
        		<td class="A">
        	{% else %}
        		<td class="normal">
    {% endif %}
	{% endcomment %}
	
	<form action="" method="post">{% csrf_token %}
	NAME <h2>{{ instrument.name }}</h2>
	<hr>
	
	DATETIME (STATUS) <h3>{{ instrument.datetime|date:"D d M Y" }} {{ instrument.datetime|time:"H:i:s" }} ({{ instrument.status }}) </h3>
	<hr>
	
	VALUE
			<h3>
				{{ form.value }}
			</h3>&nbsp;
  
  <table>
			{% if user.is_authenticated %}
			<tr><td><button class="label" type="submit" name="setValue">SET</button></td>
    		<td><button class="label" type="submit" name="setOff">OFF</button></td>
    	    <td><button class="label" type="submit" name="setOn">ON</button></td>
        	<td><button class="label" type="submit" name="resetManual"
        		{% if not instrument.manual %}
					disabled
				{% endif %}>AUTO</button></td></tr>
			 {% endif %}
			 {% if not user.is_authenticated %}
				<h1><a href="{% url 'w:login' %}">Please login to edit data.</a></h1>
			{% endif %}
  			</table>
		</form>
	</body>
</html> 	

growmat/w/templates/w/index.html
{% load staticfiles %}
<html>
	<head>
	
		<meta name="viewport" content="width=device-width">
	
		<title>GROWMAT</title>
		<meta http-equiv="refresh" content="5">
		<link rel="stylesheet" type="text/css" href="{% static 'w/style.css' %}">
    </head>

<body>
{% comment %}
<h3>
{% if user.is_authenticated %}{{ user.username }} <a href="{% url 'w:logout' %}">logout</a>{% else %}<a href="{% url 'w:login' %}">Login</a>{% endif %}
<br>
{% endcomment %}

{% comment %}
<style type="text/css">
.scrollToTop {position:fixed;bottom:50px;left:50px; border-radius: 0px;}
.scrollUp {position:fixed;bottom:50px;left:160px;border-radius: 0px;}
.scrollDown {position:fixed;bottom:50px;left:270px;border-radius: 0px;}
</style>

<script type="text/javascript">
function scrollTo(i) {
	//alert('Hello world!');
    //$(window).scrollTop(0); // If you work with jQuery,
    document.body.scrollTop =  document.body.scrollTop + i; // Or not.
}
function scrollToTop() {
    //$(window).scrollTop(0); // If you work with jQuery,
    document.body.scrollTop = 0; // Or not.
}
</script>

<button class="scrollToTop" onclick="javascript:scrollToTop();">Scroll to top</button>
<button class="scrollUp" onclick="javascript:scrollTo(-110);">Scroll up</button>
<button class="scrollDown" onclick="javascript:scrollTo(110);">Scroll down</button>
{% endcomment %}



<table>
<tr>
<td>
<a href="{% url 'w:index' %}"><button class="label">GROWMAT</button></a>
</td>
<td>
<a href="{% url 'w:instrument' %}"><button class="label">System</button></a>
</td>
<td>
<a href="{% url 'w:webcam' 0 %}"><button class="label">Webcam<br>0</button></a> 
</td>
<td>
<a href="{% url 'w:webcam' 1 %}"><button class="label">Webcam<br>1</button></a>
</td>
</tr>
</table>

<hr>
{% comment %}
{% block content %}

<table border=1>
		<tr><th>NAME</th><th>VALUE</th><th>STATUS</th></tr>
       {% for instrument in instruments %}
			{% if instrument.status > 0 and instrument.status < 4 %}
        		<tr class="NT">
        	{% elif instrument.status = 4 %}
        		<tr class="W">
        	{% elif instrument.status = 8 %}
        		<tr class="A">
        	{% else %}
        		<tr>
        	{% endif %}
            	<td>{{ instrument.name }}</td>
               	<td>{{ instrument.value }} </td>
            	<td>{{ instrument.status }} </td>
            </tr>
            
        {% endfor %}
 </table>
{% endblock %}
{% endcomment %}


<table border=0>		
        {% for instrument in instruments %}
        	{% cycle '<tr><td>' '<td>' '<td>' '<td>' %} 
        	
        	<a href="{% url 'w:detail' page instrument.id %}">
        	{% if instrument.NT %}
        		<button class="NT">
        	{% elif instrument.IV %}
        		<button class="IV">
        	{% elif instrument.W %}
        		<button class="W">
        	{% elif instrument.A %}
        		<button class="A">
        	{% else %}
        		<button class="normal">
        	{% endif %}
        	
        			{{ instrument.name }}<br/><br/>
        			<big><b>{{ instrument.value|floatformat:-3 }}</b></big><br>
        			({{ instrument.status }})
            		{% if instrument.manual %}
            			MANUAL
            		{% endif %}
        	
        	</button></a>
        	
        	{% cycle '</td>' '</td>' '</td>' '</td></tr>' %} 
        	
        {% endfor %}
       </table>
       <hr>
       <table>
        
        <tr>
        <td><a href="{% url 'w:index' '0' %}"><button class="pagebutton"><<<br>0</button></a></td>
        <td><a href="{% url 'w:index' prevpage  %}"><button class="pagebutton"><<br>{{ prevpage }}</button></a></td>
        <td><a href="{% url 'w:index' nextpage %}"><button class="pagebutton">><br>{{ nextpage }}</button></a></td>
        <td><a href="{% url 'w:index' lastpage  %}"><button class="pagebutton">>><br>{{ lastpage }}</button></a></td>
        </tr>
       </table>
{% comment %}       
<table border=0>
		{% for instrument in instruments %}
			{% cycle '<tr>' '' '' %}
			{% if instrument.NT %}
        		<td class="NT">
        	{% elif instrument.IV %}
        		<td class="IV">
        	{% elif instrument.W %}
        		<td class="W">
        	{% elif instrument.A %}
        		<td class="A">
        	{% else %}
        		<td class="normal">
        	{% endif %}
            	{% if user.is_authenticated %}
            		<a href="{% url 'w:detail' instrument.id %}"
            	{% else %}
            		<a href="{% url 'w:login' %}"
            	{% endif %}
            	<big>{{ instrument.name }}</big>
 				       
            	<h3>{{ instrument.value|floatformat:-3 }}</h3>
            	
            	({{ instrument.status }})
            	{% if instrument.manual %}
            		MANUAL
            	{% endif %}
            	</a>
            
            </td>
            {% cycle '' '' '</tr>' %}
        {% endfor %}
 </table>

{% endcomment %}


</body>
</html> 

growmat/w/templates/w/instrument.html
{% extends 'w/base.html' %}
{% block content %}


 {% if not user.is_authenticated %}
 <a href="{% url 'w:login' %}">Please login to edit data.</a>
  {% else %}
<a href="{% url 'w:instrument' 0 %}">Add Instrument</a> 
 {% endif %}




{% if form %}
	{% if form.errors %}<p><strong>{{ form.errors }}</strong></p>{% endif %}

{% endif %}

<table border=1>
		<tr><th>ID</th><th>PRI</th><th>MANUAL</th><th>NAME</th><th>ADDRESS</th><th>TYPE</th><th>INDEX</th><th>OUTPUT</th><th>DATATYPE</th><th>VALUE</th><th>STATUS</th><th>DATETIME</th><th>UPDATE</th><th>DELETE</th><th>ARCHIVE</th></tr>
		
		{% if form.pk = 0 %}
		<tr>
		<form action="" method="post">{% csrf_token %}
        	<td>NEW</td>
        	<td>{{ form.priority }}</td>
        	<td>{{ form.manual }}</td>
            <td>{{ form.name }}</td>
        	<td>{{ form.address }}</td>
            <td>{{ form.type }}</td>
            <td>{{ form.index }}</td>
            <td>{{ form.output }}</td>
            <td>{{ form.datatype }}</td>
            <td>{{ form.value }}</td>
            <td>{{ form.status }}</td>
            <td></td>
            <td><input type="submit" name="create" value="Create" /></td>
            <td></td>
            <td></td>
        </form>
        <tr>
        {% endif %}
                
        {% for instrument in instruments %}

        	{% if instrument.pk = form.pk %}
        	
        	<tr>
        	<form action="" method="post">{% csrf_token %}
            	<td>{{ form.pk }}</td>
            	<td>{{ form.priority }}</td>
        	    <td>{{ form.manual }}</td>
            	<td>{{ form.name }}</td>
            	<td>{{ form.address }}</td>
            	<td>{{ form.type }}</td>
            	<td>{{ form.index }}</td>
            	<td>{{ form.output }}</td>
            	<td>{{ form.datatype }}</td>
                <td>{{ form.value }}</td>
                <td>{{ form.status }}</td>
            	<td></td>
            	<td><input type="submit" name="save" value="Save" /></td>
            	<td></td>
            	<td></td>
            </form>
            <tr>
        	{% else %}
            <tr>
            	<td>{{ instrument.id }}</td>
            	<td>{{ instrument.priority }}</td>
            	<td>{{ instrument.manual }}</td>
            	<td>{{ instrument.name }}</td>
            	<td>{{ instrument.address }}</td>
            	<td>{{ instrument.get_type_display }}</td>
            	<td>{{ instrument.index }}</td>
            	<td>{{ instrument.output }}</td>
            	<td>{{ instrument.get_datatype_display }}</td>
               	<td>{{ instrument.value }} </td>
            	<td>{{ instrument.status }} </td>
            	<td>{{ instrument.datetime|date:"D d M Y" }} {{ instrument.datetime|time:"H:i:s" }} </td>
            	<td>{% if user.is_authenticated %}<a href="{% url 'w:instrument' instrument.id %}">Update</a>{% endif %}</td>
            	<td>{% if user.is_authenticated %}<a href="{% url 'w:instrument_delete' instrument.id %}">Delete</a>{% endif %}</td>
            	<td><a href="{% url 'w:archive' instrument.id %}">Archive</a></td>
            	 
            <tr>
            {% endif %}
        {% endfor %}
        
        
        
    
</table>

{% endblock %} 

growmat/w/templates/w/message.html
{% extends 'w/base.html' %}
{% block content %}
{{ message }}
{% endblock %} 

growmat/w/templates/w/rule.html
{% extends 'w/base.html' %}
{% block content %}



 {% if not user.is_authenticated %}
 <a href="{% url 'w:login' %}">Please login to edit data.</a>
{% else %}
<a href="{% url 'w:rule' 0 %}">Add Rule</a>
 {% endif %}
 
{% if form %}
	{% if form.errors %}<p><strong>{{ form.errors }}</strong></p>{% endif %}
{% endif %}



<table border=1>
		<tr><th>ID</th><th>PRI</th><th>PERIOD</th><th>INPUT</th><th>INPUT ATTRIBUTE</th><th>INPUT OPERATION</th><th>INPUT PARAMETER</th><th>OUTPUT</th><th>OUTPUT ATTRIBUTE</th><th>OUTPUT ACTION TRUE</th><th>OUTPUT PARAMETER TRUE</th><th>OUTPUT ACTION FALSE</th><th>OUTPUT PARAMETER FALSE</th><th>ONCE</th><th>DESCRIPTION</th><th>RESULT</th><th>DATETIME</th><th>UPDATE</th><th>DELETE</th></tr>
		{% if form.pk = 0 %}
		
		
		<tr>
		<form action="" method="post">{% csrf_token %}
        	<td>NEW</td>
        	<td>{{ form.priority }}</td>
        	<td>{{ form.period }}</td>
            <td>{{ form.input }}</td>
            <td>{{ form.input_attribute }}</td>
        	<td>{{ form.input_operation }}</td>
            <td>{{ form.input_parameter }}</td>
            <td>{{ form.output }}</td>
            <td>{{ form.output_attribute }}</td>
            <td>{{ form.output_action_true }}</td>
            <td>{{ form.output_parameter_true }}</td>
            <td>{{ form.output_action_false }}</td>
            <td>{{ form.output_parameter_false }}</td>
            <td>{{ form.once }}</td>
            <td>{{ form.description }}</td>
			<td></td>
            <td></td>
            <td><input type="submit" name="create" value="Create" /></td>
            <td></td>

        </form>
        </tr>
        {% endif %}        
        {% for rule in rules %}

        	{% if rule.pk = form.pk %}
        	
        	<tr>
        	<form action="" method="post">{% csrf_token %}
            	<td>{{ form.pk }}</td>
            	<td>{{ form.priority }}</td>
            	<td>{{ form.period }}</td>
            	<td>{{ form.input }}</td>
            	<td>{{ form.input_attribute }}</td>
        		<td>{{ form.input_operation }}</td>
            	<td>{{ form.input_parameter }}</td>
            	<td>{{ form.output }}</td>
            	<td>{{ form.output_attribute }}</td>
            	<td>{{ form.output_action_true }}</td>
            	<td>{{ form.output_parameter_true }}</td>
            	<td>{{ form.output_action_false }}</td>
            	<td>{{ form.output_parameter_false }}</td>
            	<td>{{ form.once }}</td>
            	<td>{{ form.description }}</td>
				<td></td>
            	<td></td>
            	<td><input type="submit" name="save" value="Save" /></td>
            	<td></td>
            </form>
            <tr>
        	{% else %}
            <tr>
             	<td>{{ rule.id }}</td>
             	<td>{{ rule.priority }}</td>
             	<td>{{ rule.period.name }}</td>
            	<td>{{ rule.input.name }}</td>
        		<td>{{ rule.get_input_attribute_display }}</td>
        		<td>{{ rule.get_input_operation_display }}</td>
            	<td>{{ rule.input_parameter }}</td>
            	<td>{{ rule.output.name }}</td>
            	<td>{{ rule.get_output_attribute_display }}</td>
            	<td>{{ rule.get_output_action_true_display }}</td>
            	<td>{{ rule.output_parameter_true }}</td>
            	<td>{{ rule.get_output_action_false_display }}</td>
            	<td>{{ rule.output_parameter_false }}</td>
            	<td>{{ rule.once }}</td>
            	<td>{{ rule.description }}</td>
            	<td>{{ rule.result }}</td>
            	<td>{{ rule.datetime|date:"D d M Y" }} {{ rule.datetime|time:"H:i:s" }} </td>
                <td>{% if user.is_authenticated %}<a href="{% url 'w:rule' rule.id %}">Update</a>{% endif %}</td>
            	<td>{% if user.is_authenticated %}<a href="{% url 'w:rule_delete' rule.id %}">Delete</a>{% endif %}</td>
            <tr>
            {% endif %}
        {% endfor %}
    
</table>
{% endblock %} 

growmat/w/templates/w/webcam.html
{% comment %}
{% extends 'w/base.html' %}
{% block content %}

 {% if not user.is_authenticated %}
 <a href="{% url 'w:login' %}">Please login to edit data.</a>
 {% endif %}



{% load staticfiles %}
<img src="{% static filename %}"/>


{% endblock %}
{% endcomment %}

{% load staticfiles %}
<html>
	<head>
	
		<meta name="viewport" content="width=device-width">
	
		<title>GROWMAT</title>
		<link rel="stylesheet" type="text/css" href="{% static 'w/style.css' %}">
    </head>

<body>



<table>
<tr>
<td>
<a href="{% url 'w:index' %}"><button class="label">GROWMAT</button></a>
</td>
<td>
<a href="{% url 'w:instrument' %}"><button class="label">System</button></a>
</td>
<td>
<a href="{% url 'w:webcam' 0 %}"><button class="label">Webcam<br>0</button></a> 
</td>
<td>
<a href="{% url 'w:webcam' 1 %}"><button class="label">Webcam<br>1</button></a>
</td>
</tr>
</table>

<hr>
{{ text }}
<br><br>
{% comment %}<img width="420px" src="{% static filename %}"/>{% endcomment %}
</body>
</html> 